apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::824333137275:role/eksctl-roboshop-nodegroup-roboshop-NodeInstanceRole-I044XeiEhSau
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::824333137275:user/cnu
      username: cnu
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-30T17:10:54Z"
  name: aws-auth
  namespace: kube-system
  uid: 58c0516c-c6f9-402d-b422-50bbf25e5112
